version: "2.2"
services:
  test_ui:
    build:
      context: .
      dockerfile: BlazorTestUi/Dockerfile
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp
    restart: always
